{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import telegram\n",
    "import requests\n",
    "import telegram_send\n",
    "\n",
    "import schedule\n",
    "import time\n",
    "import os\n",
    "import matplotlib.pyplot as plt\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "from bs4 import BeautifulSoup\n",
    "from telegram.ext import Updater, CommandHandler, MessageHandler, Filters\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "token = '1796099831:AAGteQJXlcNd2dLSSq0kbbqa0QoV0B_xtTU'\n",
    "    \n",
    "bot = telegram.Bot(token) #Replace TOKEN with your token string\n",
    "updater = Updater(token=token, use_context=True) #Replace TOKEN with your token string\n",
    "\n",
    "dispatcher = updater.dispatcher"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_coin_bid(coin):\n",
    "    response = requests.get('https://economia.awesomeapi.com.br/json/last/'+ coin)\n",
    "    result = response.json()\n",
    "    c = coin.replace('-','')\n",
    "    return result[c]['bid']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_bdrs_price(paper):\n",
    "    response = 'https://statusinvest.com.br/bdrs/' + paper\n",
    "    result = requests.get(response)\n",
    "    soup = BeautifulSoup(result.content, 'html.parser')\n",
    "    stock_price = str(soup.find(class_='value')).split('>')[1].split('<')[0]\n",
    "    var = str(soup.find(title='Variação do valor do ativo com base no dia anterior'))\n",
    "    \n",
    "    var = var.split('\\n')[4].split('>')[1].split('<')[0]\n",
    "        \n",
    "    if not var.startswith('-'):\n",
    "        var = '+' + var\n",
    "            \n",
    "    return stock_price, var"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_fiis_price(paper):\n",
    "    response = 'https://statusinvest.com.br/fundos-imobiliarios/' + paper\n",
    "    result = requests.get(response)\n",
    "    soup = BeautifulSoup(result.content, 'html.parser')\n",
    "    stock_price = str(soup.find(class_='value'))\n",
    "    var = str(soup.find(title='Variação do valor do ativo com base no dia anterior'))\n",
    "    \n",
    "    if stock_price == 'None':\n",
    "        return get_bdrs_price(paper)\n",
    "    else: \n",
    "        stock_price = stock_price.split('>')[1].split('<')[0]\n",
    "        var = var.split('\\n')[4].split('>')[1].split('<')[0]\n",
    "        \n",
    "        if not var.startswith('-'):\n",
    "            var = '+' + var\n",
    "            \n",
    "        return stock_price, var\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_stock_price(paper):\n",
    "    response = 'https://statusinvest.com.br/acoes/' + paper\n",
    "    result = requests.get(response)\n",
    "    soup = BeautifulSoup(result.content, 'html.parser')\n",
    "    stock_price = str(soup.find(class_='value'))\n",
    "    var = str(soup.find(title='Variação do valor do ativo com base no dia anterior'))\n",
    "    \n",
    "    if stock_price == 'None':\n",
    "        return get_fiis_price(paper)\n",
    "    else: \n",
    "        \n",
    "        stock_price = stock_price.split('>')[1].split('<')[0]\n",
    "        var = var.split('\\n')[4].split('>')[1].split('<')[0]\n",
    "        \n",
    "        if not var.startswith('-'):\n",
    "            var = '+' + var\n",
    "            \n",
    "        return stock_price, var\n",
    "    \n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def stock(update, context):\n",
    "    paper = \" \".join(context.args)\n",
    "    value = get_stock_price(paper.lower())\n",
    "    update.message.reply_text(paper.upper() + \": R$\" + value[0] + '\\n \\n Variação do dia: ' + value[1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def euro(update, context):\n",
    "    eur = \"Cotação do Euro Hoje: R$ \" + str(get_coin_bid('EUR-BRL')).replace('.',',')\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=eur)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def vilzyn(update, context):\n",
    "    dol = \"Cotação do Dolar Hoje: R$ \" + str(get_coin_bid('USD-BRL')).replace('.',',')\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=dol)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def dolar(update, context):\n",
    "    dol = \"Cotação do Dolar Hoje: R$ \" + str(get_coin_bid('USD-BRL')).replace('.',',')\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=dol)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def hello(update, context):\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text='Eai Kamako')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def chart(update, context):\n",
    "    paper = \" \".join(context.args)\n",
    "    get_stock_chart(paper)\n",
    "    context.bot.sendPhoto(chat_id=update.effective_chat.id, photo=open(paper + '.png', 'rb'))\n",
    "    os.remove(paper + '.png')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd # Para evitar escrever pandas e trocar pela escrita apenas de pd para facilitar\n",
    "import plotly.graph_objects as go\n",
    "import matplotlib.pyplot as plt\n",
    "import yfinance as yf \n",
    "\n",
    "from pandas_datareader import data as web # Evita a escrita do data e troca pelo web\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "def get_stock_chart(paper):\n",
    "    paper_data = yf.download(\n",
    "    tickers=paper + '.SA', \n",
    "    period=\"1d\",\n",
    "    interval=\"1m\")\n",
    "    \n",
    "    plt.plot(paper_data['Close'])\n",
    "    plt.savefig(paper + '.png')\n",
    "    plt.clf()\n",
    "    return paper_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_stock_chart(paper):\n",
    "    data = yf.download(\n",
    "    tickers=paper + '.SA', \n",
    "    period=\"3mo\",\n",
    "    interval=\"1d\")\n",
    "    # Plot the close prices\n",
    "\n",
    "    data = data.reset_index()\n",
    "    data = data.rename(columns={data.columns[0]:'Date'})\n",
    "    \n",
    "    fig = go.Figure(data=[go.Candlestick(x=data['Date'],\n",
    "                open=data['Open'],\n",
    "                high=data['High'],\n",
    "                low=data['Low'],\n",
    "                close=data['Close'])])\n",
    "    fig.update_layout(xaxis_rangeslider_visible=False)\n",
    "    fig.write_image(paper + '.png')\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "dispatcher.add_handler(CommandHandler('hello', hello))\n",
    "dispatcher.add_handler(CommandHandler('dolar', dolar))\n",
    "dispatcher.add_handler(CommandHandler('euro', euro))\n",
    "dispatcher.add_handler(CommandHandler('vilzyn', vilzyn))\n",
    "\n",
    "dispatcher.add_handler(CommandHandler(\"stock\", stock))\n",
    "dispatcher.add_handler(CommandHandler(\"chart\", chart))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<queue.Queue at 0x278c15f9e50>"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 520, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 471, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 127, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2761, in get_updates\n",
      "    result = self._post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 259, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 350, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\pedrotcheu\\Anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 277, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "updater.start_polling()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
